import React from 'react';
import { Series, AbsoluteFill, Video, Img, useVideoConfig } from 'remotion';
import { SentinelManifest } from './types';

export const DynamicVideo: React.FC<{ manifest: SentinelManifest }> = ({ manifest }) => {
    const { fps } = useVideoConfig();

    return (
        <AbsoluteFill style={{ backgroundColor: 'black' }}>
            <Series>
                {/* Intro / Title Card */}
                <Series.Sequence durationInFrames={3 * fps}>
                    <AbsoluteFill style={{
                        backgroundColor: '#111',
                        justifyContent: 'center',
                        alignItems: 'center',
                        color: 'white',
                        fontFamily: 'sans-serif'
                    }}>
                        <h1 style={{ fontSize: 80, margin: 0 }}>{manifest.title}</h1>
                        <p style={{ fontSize: 30, opacity: 0.8 }}>{manifest.description}</p>
                    </AbsoluteFill>
                </Series.Sequence>

                {/* Clips */}
                {manifest.clips.map((clip, index) => (
                    <Series.Sequence key={index} durationInFrames={clip.durationInSec * fps}>
                        {clip.type === 'video' && clip.src && (
                            <Video src={clip.src} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                        )}
                        {clip.type === 'image' && clip.src && (
                            <Img src={clip.src} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                        )}
                        {clip.type === 'text' && clip.text && (
                            <AbsoluteFill style={{
                                backgroundColor: '#222',
                                justifyContent: 'center',
                                alignItems: 'center',
                                color: '#eee',
                                fontFamily: 'monospace',
                                padding: 60,
                                textAlign: 'center'
                            }}>
                                <div style={{ fontSize: 50 }}>{clip.text}</div>
                            </AbsoluteFill>
                        )}
                    </Series.Sequence>
                ))}

                {/* Outro */}
                <Series.Sequence durationInFrames={3 * fps}>
                    <AbsoluteFill style={{
                        backgroundColor: '#000',
                        justifyContent: 'center',
                        alignItems: 'center',
                        color: 'white',
                        fontFamily: 'sans-serif'
                    }}>
                        <h2 style={{ fontSize: 60 }}>SENTINEL CORTEX</h2>
                        <p>Generated by AI</p>
                    </AbsoluteFill>
                </Series.Sequence>
            </Series>
        </AbsoluteFill>
    );
};
