[package]
name = "sentinel_media_obs_agent"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "obs-agente"
path = "src/main.rs"


[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
ignore = "0.4"
# me60os_core = { path = "../libs/me60os", package = "me60os" }
regex = "1.10"
clap = { version = "4.5", features = ["derive"] }
sha2 = "0.10"
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
sentinel_media_core = { path = "../sentinel_media_core" }
sentinel_media_memory = { path = "../sentinel_media_memory" }
